from django.urls import path

from .views import (
    AppDataBootstrapView,
    AtivoDetailView,
    AtivoListCreateView,
    AtivoMaintenanceListCreateView,
    CategoryConfigDetailView,
    CategoryConfigListCreateView,
    ExternalPlatformDetailView,
    ExternalPlatformListCreateView,
    HealthCheckView,
    InfraLocationConfigDetailView,
    InfraLocationConfigListCreateView,
    InternalAppDetailView,
    InternalAppListCreateView,
    LoginView,
    LogoutView,
    MeView,
    NotificationRecipientDetailView,
    NotificationRecipientListCreateView,
    PublicCategoryListView,
    PublicInfraLocationListView,
    PublicMatriculaListView,
    PublicTicketCreateView,
    RegisterView,
    SLAConfigListView,
    SLAConfigUpdateView,
    SystemUserDetailView,
    SystemUserListCreateView,
    TicketCommentCreateView,
    TicketCreateView,
    TicketDetailView,
    TicketExecutionListCreateView,
    TicketHistoryListView,
    WhatsappChatMessageStreamView,
    WhatsappChatMessagesView,
    WhatsappChatSessionStreamView,
    WhatsappChatSessionListView,
    WhatsappSessionStatusView,
    WhatsappTicketContactView,
    WhatsappBotManagementView,
    WhatsappWebhookView,
)

urlpatterns = [
    path("health/", HealthCheckView.as_view(), name="health-check"),
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/me/", MeView.as_view(), name="auth-me"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("public/matriculas/", PublicMatriculaListView.as_view(), name="public-matriculas"),
    path("public/categories/", PublicCategoryListView.as_view(), name="public-categories"),
    path("public/infra-locations/", PublicInfraLocationListView.as_view(), name="public-infra-locations"),
    path("public/tickets/", PublicTicketCreateView.as_view(), name="public-tickets-create"),
    path("app-data/bootstrap/", AppDataBootstrapView.as_view(), name="app-data-bootstrap"),
    path("settings/categories/", CategoryConfigListCreateView.as_view(), name="settings-categories-list-create"),
    path("settings/categories/<int:category_id>/", CategoryConfigDetailView.as_view(), name="settings-categories-detail"),
    path("settings/infra-locations/", InfraLocationConfigListCreateView.as_view(), name="settings-infra-locations-list-create"),
    path("settings/infra-locations/<int:location_id>/", InfraLocationConfigDetailView.as_view(), name="settings-infra-locations-detail"),
    path(
        "settings/notification-recipients/",
        NotificationRecipientListCreateView.as_view(),
        name="settings-notification-recipients-list-create",
    ),
    path(
        "settings/notification-recipients/<int:recipient_id>/",
        NotificationRecipientDetailView.as_view(),
        name="settings-notification-recipients-detail",
    ),
    path("settings/sla/", SLAConfigListView.as_view(), name="settings-sla-list"),
    path("settings/sla/update/", SLAConfigUpdateView.as_view(), name="settings-sla-update"),
    path("settings/users/", SystemUserListCreateView.as_view(), name="settings-users-list-create"),
    path("settings/users/<int:user_id>/", SystemUserDetailView.as_view(), name="settings-users-detail"),
    path("settings/apps/", InternalAppListCreateView.as_view(), name="settings-apps-list-create"),
    path("settings/apps/<int:app_id>/", InternalAppDetailView.as_view(), name="settings-apps-detail"),
    path("settings/external-platforms/", ExternalPlatformListCreateView.as_view(), name="settings-external-platforms-list-create"),
    path("settings/external-platforms/<int:platform_id>/", ExternalPlatformDetailView.as_view(), name="settings-external-platforms-detail"),
    path("ativos/", AtivoListCreateView.as_view(), name="ativos-list-create"),
    path("ativos/<int:ativo_id>/", AtivoDetailView.as_view(), name="ativos-detail"),
    path("ativos/<int:ativo_id>/maintenance/", AtivoMaintenanceListCreateView.as_view(), name="ativos-maintenance"),
    path("whatsapp/sessions/", WhatsappSessionStatusView.as_view(), name="whatsapp-sessions"),
    path("whatsapp/messages/", WhatsappTicketContactView.as_view(), name="whatsapp-messages"),
    path("whatsapp/chats/", WhatsappChatSessionListView.as_view(), name="whatsapp-chats"),
    path("whatsapp/chats/stream/", WhatsappChatSessionStreamView.as_view(), name="whatsapp-chats-stream"),
    path("whatsapp/chats/<str:numero>/messages/", WhatsappChatMessagesView.as_view(), name="whatsapp-chat-messages"),
    path("whatsapp/chats/<str:numero>/messages/stream/", WhatsappChatMessageStreamView.as_view(), name="whatsapp-chat-messages-stream"),
    path("whatsapp/webhook/", WhatsappWebhookView.as_view(), name="whatsapp-webhook"),
    path("whatsapp/bot/", WhatsappBotManagementView.as_view(), name="whatsapp-bot"),
    path("tickets/", TicketCreateView.as_view(), name="tickets-create"),
    path("tickets/<str:ticket_id>/", TicketDetailView.as_view(), name="tickets-detail"),
    path("tickets/<str:ticket_id>/comments/", TicketCommentCreateView.as_view(), name="tickets-comments-create"),
    path("tickets/<str:ticket_id>/executions/", TicketExecutionListCreateView.as_view(), name="tickets-executions-list-create"),
    path("tickets/<str:ticket_id>/history/", TicketHistoryListView.as_view(), name="tickets-history-list"),
]
