# Generated by Django 5.2.8 on 2026-04-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesterprofile',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='WhatsApp'),
        ),
    ]
