# Generated by Django 5.2.8 on 2026-09-11 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0010_ticket_is_rescheduled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MondaySubitemTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_subitem_id', models.CharField(max_length=50, unique=True, verbose_name='Subelemento (Monday)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Convertido por')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monday_subitem_links', to='tickets.ticket', verbose_name='Chamado')),
            ],
            options={
                'verbose_name': 'Vínculo Monday -> Ticket',
                'verbose_name_plural': 'Vínculos Monday -> Ticket',
            },
        ),
    ]
