# Generated by Django 4.2.16 on 2026-04-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('app_type', models.CharField(choices=[('INTERNAL', 'Interno'), ('EXTERNAL', 'Externo')], max_length=20, verbose_name='Tipo')),
                ('vendor', models.CharField(blank=True, max_length=120, verbose_name='Fornecedor')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aplicativo',
                'verbose_name_plural': 'Aplicativos',
                'ordering': ['name'],
            },
        ),
    ]
