# Generated by Django 4.2.16 on 2026-04-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='vendor',
            new_name='responsible',
        ),
        migrations.AddField(
            model_name='application',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de lançamento'),
        ),
    ]
