# Generated by Django 4.2.29 on 2026-04-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_application_vendor_application_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='responsible',
            field=models.CharField(blank=True, max_length=120, verbose_name='Responsável'),
        ),
    ]
