# Generated by Django 4.2.29 on 2026-06-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_asset_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Oculto'),
        ),
    ]
