# Generated by Django 5.2.8 on 2026-08-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_rescheduled',
            field=models.BooleanField(default=False, verbose_name='Reprogramada'),
        ),
    ]
