# Generated by Django 4.2.16 on 2026-04-02 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=50, unique=True, verbose_name='Patrimônio')),
                ('asset_type', models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('DESKTOP', 'Desktop'), ('PHONE', 'Celular'), ('TABLET', 'Tablet'), ('PRINTER', 'Impressora'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='Tipo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Número de série')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Sistema operacional')),
                ('specs', models.JSONField(blank=True, default=dict, verbose_name='Especificações')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('MAINTENANCE', 'Em manutenção'), ('RETIRED', 'Desativado'), ('STORAGE', 'Em estoque')], default='ACTIVE', max_length=15, verbose_name='Status')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localização')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Data de compra')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Garantia até')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='accounts.requesterprofile', verbose_name='Responsável (colaborador)')),
                ('assigned_to_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='Responsável (equipe TI)')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ASSIGNED', 'Atribuído'), ('UNASSIGNED', 'Desatribuído'), ('STATUS_CHANGE', 'Mudança de status'), ('MAINTENANCE', 'Manutenção')], max_length=20, verbose_name='Ação')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assets.asset', verbose_name='Ativo')),
                ('new_assignee_requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_history_new', to='accounts.requesterprofile')),
                ('new_assignee_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_history_new', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('previous_assignee_requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_history_previous', to='accounts.requesterprofile')),
                ('previous_assignee_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_history_previous', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico do ativo',
                'verbose_name_plural': 'Histórico dos ativos',
                'ordering': ['-created_at'],
            },
        ),
    ]
