# Generated by Django 5.2.8 on 2026-06-05 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número')),
                ('matricula', models.CharField(max_length=50, verbose_name='Matrícula')),
                ('requester_name', models.CharField(max_length=200, verbose_name='Nome do responsável')),
                ('setor', models.CharField(max_length=200, verbose_name='Setor')),
                ('software_name', models.CharField(max_length=200, verbose_name='Nome do software')),
                ('software_url', models.URLField(blank=True, verbose_name='Site / URL do software')),
                ('reason', models.TextField(verbose_name='Motivo / Justificativa')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando análise'), ('IN_REVIEW', 'Em análise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Reprovado')], default='PENDING', max_length=15, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da análise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Analisado por')),
            ],
            options={
                'verbose_name': 'Solicitação de software',
                'verbose_name_plural': 'Solicitações de software',
                'ordering': ['-created_at'],
            },
        ),
    ]
