# Generated by Django 5.2.8 on 2026-06-05 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwarerequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='softwarerequest',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='softwarerequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='softwarerequest',
            name='status',
        ),
        migrations.AddField(
            model_name='softwarerequest',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo estimado (R$)'),
        ),
        migrations.AddField(
            model_name='softwarerequest',
            name='estimated_users',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº estimado de usuários'),
        ),
        migrations.AddField(
            model_name='softwarerequest',
            name='needs_director_approval',
            field=models.BooleanField(default=False, verbose_name='Requer aval da diretoria'),
        ),
        migrations.AddField(
            model_name='softwarerequest',
            name='stage',
            field=models.CharField(choices=[('SUBMITTED', 'Solicitação recebida'), ('TI_ANALYSIS', 'Análise da TI'), ('DIRECTOR_APPROVAL', 'Aguardando aval da diretoria'), ('IMPLEMENTATION', 'Em implantação'), ('COMPLETED', 'Concluído'), ('REJECTED', 'Reprovado')], default='SUBMITTED', max_length=25, verbose_name='Etapa'),
        ),
        migrations.CreateModel(
            name='SoftwareRequestStageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, max_length=25, verbose_name='De')),
                ('to_stage', models.CharField(max_length=25, verbose_name='Para')),
                ('observation', models.TextField(blank=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_stage_logs', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('software_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='software_requests.softwarerequest', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Registro de etapa',
                'verbose_name_plural': 'Registros de etapa',
                'ordering': ['created_at'],
            },
        ),
    ]
