# Generated by Django 6.0.1 on 2026-02-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ticket_id', models.CharField(max_length=50)),
                ('author_id', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('area', models.CharField(max_length=20)),
                ('dono_id', models.CharField(max_length=50)),
                ('membros_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('projeto_id', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-data_inicio', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('area', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=50)),
                ('prioridade', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=40)),
                ('kanban_column', models.CharField(blank=True, max_length=20, null=True)),
                ('solicitante_id', models.CharField(max_length=50)),
                ('responsavel_id', models.CharField(blank=True, max_length=50, null=True)),
                ('projeto_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sprint_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sla_due_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('checklist', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
