# Generated by Django 6.0.1 on 2026-02-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.CharField(max_length=20, unique=True)),
                ('horas', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
