# Generated by Django 6.0.1 on 2026-02-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slaconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_id', models.CharField(max_length=50)),
                ('author_id', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(max_length=50)),
                ('field', models.CharField(blank=True, max_length=50, null=True)),
                ('from_value', models.TextField(blank=True, null=True)),
                ('to_value', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
