# Generated by Django 6.0.1 on 2026-02-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tickethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='execution_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='execution_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
