# Generated by Django 6.0.1 on 2026-02-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ticket_execution_end_at_ticket_execution_start_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketExecution',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_id', models.CharField(max_length=50)),
                ('author_id', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['started_at', 'id'],
            },
        ),
    ]
