# Generated by Django 6.0.1 on 2026-02-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ticketexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['area', 'nome', 'id'],
                'constraints': [models.UniqueConstraint(fields=('area', 'nome'), name='uniq_category_area_nome')],
            },
        ),
    ]
