# Generated by Django 6.0.1 on 2026-02-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notificationrecipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalApp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, default='')),
                ('data_lancamento', models.DateField()),
            ],
            options={
                'ordering': ['nome', 'id'],
            },
        ),
    ]
