# Generated by Django 6.0.1 on 2026-02-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_internalapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='numero_tombamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
