# Generated by Django 6.0.1 on 2026-02-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ticket_numero_tombamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='maquina_parada',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
