# Generated by Django 6.0.1 on 2026-02-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraLocationConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='localizacao_problema',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
