# Generated by Django 6.0.1 on 2026-03-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_externalplatform_data_implantacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('tipo_aparelho', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=100)),
                ('numero_tombamento', models.CharField(blank=True, default='', max_length=100)),
                ('responsavel', models.CharField(blank=True, default='', max_length=150)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('entregue_por', models.CharField(blank=True, default='', max_length=150)),
                ('localizacao', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('ativo', 'Em uso'), ('disponivel', 'Disponível'), ('manutencao', 'Em manutenção'), ('descartado', 'Descartado')], default='disponivel', max_length=30)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['descricao', 'id'],
            },
        ),
    ]
