# Generated by Django 6.0.1 on 2026-03-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
