# Generated by Django 6.0.1 on 2026-03-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_whatsapp_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappsession",
            name="bot_context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
