# Generated by Django 6.0.1 on 2026-03-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_whatsappsession_bot_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="telefone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]

