# Generated by Django 6.0.1 on 2026-03-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_userprofile_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationrecipient",
            name="telefone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]

